version: "3"

services:
 node:
  build:
   context: ./backend
   dockerfile: docker/Dockerfile
  container_name: api
  command: npm run dev
  depends_on:
    - mysql
  ports:
   - 3001:3001
  volumes:
   - ./backend/src:/app/src
  networks:
   - api-network
 react:
   build:
     context: ./frontend
     dockerfile: docker/Dockerfile
   container_name: frontend
   command: npm start
   stdin_open: true
   ports:
     - 3000:3000
   volumes:
     - ./frontend/src:/app/src
     - ./frontend/public:/app/public
   depends_on:
    - node
   networks:
     - api-network
 mysql:
   image: mysql:5.7
   container_name: "mysql"
   command: mysqld --sql_mode=""
   ports:
    - "3306:3306"
   environment:
    - MYSQL_ROOT_PASSWORD=root
   volumes:
     - ./docker-entrypoint-initdb.d/init.sql:/docker-entrypoint-initdb.d/init.sql
     - mysql_volume:/var/lib/mysql
   networks:
    - api-network

volumes:
 mysql_volume:
 npm-cache:
  external: false

networks:
 api-network: