version: "3"

services:
 node:
  build:
   context: ..
   dockerfile: docker/Dockerfile
  container_name: api
  command: npm run dev
  ports:
   - 3000:3000
  volumes:
   - ../src:/app/src
  networks:
   - api-network
 mysql:
   image: mysql:5.7
   container_name: "mysql"
   command: mysqld --sql_mode=""
   ports:
    - "3306:3306"
   environment:
    - MYSQL_ROOT_PASSWORD=root
   volumes:
     - ./docker-entrypoint-initdb.d/init.sql:/docker-entrypoint-initdb.d/init.sql
     - mysql_volume:/var/lib/mysql
   networks:
    - api-network

volumes:
 mysql_volume:
 npm-cache:
  external: false

networks:
 api-network: